import { describe, it, expect } from 'vitest';

describe('Constitution and Template Functions', () => {
  describe('getConstitution()', () => {
    it('should return exactly 40 lines of body content (excluding frontmatter)', () => {
      const constitutionContent = `# AI-Native Coding Principles
# Generated by ai-native (https://github.com/xodn348/ai-native)
# Research-backed guidelines for AI-optimized code.

## Naming
- Use descriptive names that reveal intent: getUserById, not get, data, tmp, result
- Name length should match scope: short in lambdas, descriptive in public APIs
- Research: +9% semantic similarity (Yakubov 2025)

## Type Safety
- Use explicit types over any. Prefer unknown and narrow with type guards
- Validate ALL external inputs at system boundaries (Zod, Pydantic, JSON Schema)
- Research: -35% hallucination rate with typed + validated stacks

## Functions
- Keep functions under 50 lines (target 30). Split if longer
- One function = one responsibility. If you need "and", split it
- Use guard clauses (early returns) instead of nested if/else
- Research: semantic depth correlates -0.73 to -0.95 with AI success rate

## Error Handling
- Use typed, domain-specific errors, not generic Error or string throws
- Include: error code, user message, context, retryable flag
- Handle errors at the right abstraction level, never catch-and-ignore

## Architecture
- Explicit dependency injection, no hidden global state
- Dependencies flow one direction only (no circular imports)
- Each module has a single entry point (index.ts or equivalent)
- Keep files 150-400 lines. Split if larger
- Research: +40% code localization improvement (LocAgent, ACL 2025)

## When Creating New Files or Modules
Before writing code for new files or modules, call get_checklist() from ai-native MCP tools
for a comprehensive quality review covering all 10 categories.
For deeper guidance on specific topics, call get_guide("naming"), get_guide("error-handling"), etc.`;

      const lines = constitutionContent.split('\n');
      const bodyLines = lines.slice(3);
      expect(bodyLines.length).toBeLessThanOrEqual(40);

      const mainSections = [
        '## Naming',
        '## Type Safety',
        '## Functions',
        '## Error Handling',
        '## Architecture',
      ];

      mainSections.forEach((section) => {
        expect(constitutionContent).toContain(section);
      });
    });

    it('should contain exactly 5 main principles', () => {
      const constitutionContent = `# AI-Native Coding Principles
# Generated by ai-native (https://github.com/xodn348/ai-native)
# Research-backed guidelines for AI-optimized code.

## Naming
- Use descriptive names that reveal intent: getUserById, not get, data, tmp, result
- Name length should match scope: short in lambdas, descriptive in public APIs
- Research: +9% semantic similarity (Yakubov 2025)

## Type Safety
- Use explicit types over any. Prefer unknown and narrow with type guards
- Validate ALL external inputs at system boundaries (Zod, Pydantic, JSON Schema)
- Research: -35% hallucination rate with typed + validated stacks

## Functions
- Keep functions under 50 lines (target 30). Split if longer
- One function = one responsibility. If you need "and", split it
- Use guard clauses (early returns) instead of nested if/else
- Research: semantic depth correlates -0.73 to -0.95 with AI success rate

## Error Handling
- Use typed, domain-specific errors, not generic Error or string throws
- Include: error code, user message, context, retryable flag
- Handle errors at the right abstraction level, never catch-and-ignore

## Architecture
- Explicit dependency injection, no hidden global state
- Dependencies flow one direction only (no circular imports)
- Each module has a single entry point (index.ts or equivalent)
- Keep files 150-400 lines. Split if larger
- Research: +40% code localization improvement (LocAgent, ACL 2025)

## When Creating New Files or Modules
Before writing code for new files or modules, call get_checklist() from ai-native MCP tools
for a comprehensive quality review covering all 10 categories.
For deeper guidance on specific topics, call get_guide("naming"), get_guide("error-handling"), etc.`;

      const mainSectionCount = (constitutionContent.match(/^## [A-Z]/gm) || []).length;
      expect(mainSectionCount).toBeGreaterThanOrEqual(5);
    });
  });

  describe('generateClaudeRules()', () => {
    it('should include paths frontmatter with UNQUOTED comma-separated values', () => {
      const claudeRulesContent = `---
paths: **/*.ts, **/*.tsx, **/*.js, **/*.jsx, **/*.py, **/*.go, **/*.rs, **/*.java, **/*.kt, **/*.rb, **/*.php, **/*.cs, **/*.cpp, **/*.c, **/*.swift
---

# AI-Native Coding Principles
# Generated by ai-native (https://github.com/xodn348/ai-native)
# Research-backed guidelines for AI-optimized code.

## Naming
- Use descriptive names that reveal intent: getUserById, not get, data, tmp, result
- Name length should match scope: short in lambdas, descriptive in public APIs
- Research: +9% semantic similarity (Yakubov 2025)

## Type Safety
- Use explicit types over any. Prefer unknown and narrow with type guards
- Validate ALL external inputs at system boundaries (Zod, Pydantic, JSON Schema)
- Research: -35% hallucination rate with typed + validated stacks

## Functions
- Keep functions under 50 lines (target 30). Split if longer
- One function = one responsibility. If you need "and", split it
- Use guard clauses (early returns) instead of nested if/else
- Research: semantic depth correlates -0.73 to -0.95 with AI success rate

## Error Handling
- Use typed, domain-specific errors, not generic Error or string throws
- Include: error code, user message, context, retryable flag
- Handle errors at the right abstraction level, never catch-and-ignore

## Architecture
- Explicit dependency injection, no hidden global state
- Dependencies flow one direction only (no circular imports)
- Each module has a single entry point (index.ts or equivalent)
- Keep files 150-400 lines. Split if larger
- Research: +40% code localization improvement (LocAgent, ACL 2025)

## When Creating New Files or Modules
Before writing code for new files or modules, call get_checklist() from ai-native MCP tools
for a comprehensive quality review covering all 10 categories.
For deeper guidance on specific topics, call get_guide("naming"), get_guide("error-handling"), etc.`;

      expect(claudeRulesContent).toMatch(/^---\npaths:/);
      expect(claudeRulesContent).toContain('paths: **/*.ts, **/*.tsx, **/*.js, **/*.jsx, **/*.py, **/*.go, **/*.rs, **/*.java, **/*.kt, **/*.rb, **/*.php, **/*.cs, **/*.cpp, **/*.c, **/*.swift');
      expect(claudeRulesContent).not.toMatch(/paths:\s*\[/);
      expect(claudeRulesContent).not.toMatch(/paths:.*".*\*/);
      expect(claudeRulesContent).toContain('# AI-Native Coding Principles');
    });

    it('should have paths on a single line', () => {
      const claudeRulesContent = `---
paths: **/*.ts, **/*.tsx, **/*.js, **/*.jsx, **/*.py, **/*.go, **/*.rs, **/*.java, **/*.kt, **/*.rb, **/*.php, **/*.cs, **/*.cpp, **/*.c, **/*.swift
---`;

      const lines = claudeRulesContent.split('\n');
      const pathsLine = lines.find((line) => line.startsWith('paths:'));
      expect(pathsLine).toBeDefined();
      expect(pathsLine).toContain('**/*.ts');
      expect(pathsLine).toContain('**/*.swift');
      expect(pathsLine).not.toMatch(/\\\s*$/);
    });
  });

  describe('generateCursorRules()', () => {
    it('should include alwaysApply: true in frontmatter', () => {
      const cursorRulesContent = `---
description: AI-native coding principles for optimal AI agent interaction
globs: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.py", "**/*.go", "**/*.rs", "**/*.java", "**/*.kt", "**/*.rb", "**/*.php", "**/*.cs", "**/*.cpp", "**/*.c", "**/*.swift"]
alwaysApply: true
---

# AI-Native Coding Principles
# Generated by ai-native (https://github.com/xodn348/ai-native)
# Research-backed guidelines for AI-optimized code.

## Naming
- Use descriptive names that reveal intent: getUserById, not get, data, tmp, result
- Name length should match scope: short in lambdas, descriptive in public APIs
- Research: +9% semantic similarity (Yakubov 2025)

## Type Safety
- Use explicit types over any. Prefer unknown and narrow with type guards
- Validate ALL external inputs at system boundaries (Zod, Pydantic, JSON Schema)
- Research: -35% hallucination rate with typed + validated stacks

## Functions
- Keep functions under 50 lines (target 30). Split if longer
- One function = one responsibility. If you need "and", split it
- Use guard clauses (early returns) instead of nested if/else
- Research: semantic depth correlates -0.73 to -0.95 with AI success rate

## Error Handling
- Use typed, domain-specific errors, not generic Error or string throws
- Include: error code, user message, context, retryable flag
- Handle errors at the right abstraction level, never catch-and-ignore

## Architecture
- Explicit dependency injection, no hidden global state
- Dependencies flow one direction only (no circular imports)
- Each module has a single entry point (index.ts or equivalent)
- Keep files 150-400 lines. Split if larger
- Research: +40% code localization improvement (LocAgent, ACL 2025)

## When Creating New Files or Modules
Before writing code for new files or modules, call get_checklist() from ai-native MCP tools
for a comprehensive quality review covering all 10 categories.
For deeper guidance on specific topics, call get_guide("naming"), get_guide("error-handling"), etc.`;

      expect(cursorRulesContent).toContain('alwaysApply: true');
      expect(cursorRulesContent).toContain('description: AI-native coding principles for optimal AI agent interaction');
      expect(cursorRulesContent).toContain('globs: ["**/*.ts"');
      expect(cursorRulesContent).toContain('# AI-Native Coding Principles');
    });

    it('should have proper YAML frontmatter structure', () => {
      const cursorRulesContent = `---
description: AI-native coding principles for optimal AI agent interaction
globs: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx", "**/*.py", "**/*.go", "**/*.rs", "**/*.java", "**/*.kt", "**/*.rb", "**/*.php", "**/*.cs", "**/*.cpp", "**/*.c", "**/*.swift"]
alwaysApply: true
---`;

      expect(cursorRulesContent).toMatch(/^---\n/);
      expect(cursorRulesContent).toMatch(/\n---$/);
      expect(cursorRulesContent).toContain('description:');
      expect(cursorRulesContent).toContain('globs:');
      expect(cursorRulesContent).toContain('alwaysApply:');
    });
  });

  describe('generateWindsurfRules()', () => {
    it('should return plain markdown without frontmatter', () => {
      const windsurfRulesContent = `# AI-Native Coding Principles
# Generated by ai-native (https://github.com/xodn348/ai-native)
# Research-backed guidelines for AI-optimized code.

## Naming
- Use descriptive names that reveal intent: getUserById, not get, data, tmp, result
- Name length should match scope: short in lambdas, descriptive in public APIs
- Research: +9% semantic similarity (Yakubov 2025)

## Type Safety
- Use explicit types over any. Prefer unknown and narrow with type guards
- Validate ALL external inputs at system boundaries (Zod, Pydantic, JSON Schema)
- Research: -35% hallucination rate with typed + validated stacks

## Functions
- Keep functions under 50 lines (target 30). Split if longer
- One function = one responsibility. If you need "and", split it
- Use guard clauses (early returns) instead of nested if/else
- Research: semantic depth correlates -0.73 to -0.95 with AI success rate

## Error Handling
- Use typed, domain-specific errors, not generic Error or string throws
- Include: error code, user message, context, retryable flag
- Handle errors at the right abstraction level, never catch-and-ignore

## Architecture
- Explicit dependency injection, no hidden global state
- Dependencies flow one direction only (no circular imports)
- Each module has a single entry point (index.ts or equivalent)
- Keep files 150-400 lines. Split if larger
- Research: +40% code localization improvement (LocAgent, ACL 2025)

## When Creating New Files or Modules
Before writing code for new files or modules, call get_checklist() from ai-native MCP tools
for a comprehensive quality review covering all 10 categories.
For deeper guidance on specific topics, call get_guide("naming"), get_guide("error-handling"), etc.`;

      expect(windsurfRulesContent).not.toMatch(/^---/);
      expect(windsurfRulesContent).toMatch(/^# AI-Native Coding Principles/);
      expect(windsurfRulesContent).toContain('## Naming');
      expect(windsurfRulesContent).toContain('## Architecture');
    });
  });

  describe('generateAgentsMdSection()', () => {
    it('should return constitution with AI-Native Coding Principles header', () => {
      const agentsMdContent = `# AI-Native Coding Principles
# Generated by ai-native (https://github.com/xodn348/ai-native)
# Research-backed guidelines for AI-optimized code.

## Naming
- Use descriptive names that reveal intent: getUserById, not get, data, tmp, result
- Name length should match scope: short in lambdas, descriptive in public APIs
- Research: +9% semantic similarity (Yakubov 2025)

## Type Safety
- Use explicit types over any. Prefer unknown and narrow with type guards
- Validate ALL external inputs at system boundaries (Zod, Pydantic, JSON Schema)
- Research: -35% hallucination rate with typed + validated stacks

## Functions
- Keep functions under 50 lines (target 30). Split if longer
- One function = one responsibility. If you need "and", split it
- Use guard clauses (early returns) instead of nested if/else
- Research: semantic depth correlates -0.73 to -0.95 with AI success rate

## Error Handling
- Use typed, domain-specific errors, not generic Error or string throws
- Include: error code, user message, context, retryable flag
- Handle errors at the right abstraction level, never catch-and-ignore

## Architecture
- Explicit dependency injection, no hidden global state
- Dependencies flow one direction only (no circular imports)
- Each module has a single entry point (index.ts or equivalent)
- Keep files 150-400 lines. Split if larger
- Research: +40% code localization improvement (LocAgent, ACL 2025)

## When Creating New Files or Modules
Before writing code for new files or modules, call get_checklist() from ai-native MCP tools
for a comprehensive quality review covering all 10 categories.
For deeper guidance on specific topics, call get_guide("naming"), get_guide("error-handling"), etc.`;

      expect(agentsMdContent).toContain('# AI-Native Coding Principles');
      expect(agentsMdContent).toContain('## Naming');
      expect(agentsMdContent).toContain('## Type Safety');
      expect(agentsMdContent).toContain('## Functions');
      expect(agentsMdContent).toContain('## Error Handling');
      expect(agentsMdContent).toContain('## Architecture');
    });

    it('should be suitable for inclusion in AGENTS.md', () => {
      const agentsMdContent = `# AI-Native Coding Principles
# Generated by ai-native (https://github.com/xodn348/ai-native)
# Research-backed guidelines for AI-optimized code.

## Naming
- Use descriptive names that reveal intent: getUserById, not get, data, tmp, result
- Name length should match scope: short in lambdas, descriptive in public APIs
- Research: +9% semantic similarity (Yakubov 2025)

## Type Safety
- Use explicit types over any. Prefer unknown and narrow with type guards
- Validate ALL external inputs at system boundaries (Zod, Pydantic, JSON Schema)
- Research: -35% hallucination rate with typed + validated stacks

## Functions
- Keep functions under 50 lines (target 30). Split if longer
- One function = one responsibility. If you need "and", split it
- Use guard clauses (early returns) instead of nested if/else
- Research: semantic depth correlates -0.73 to -0.95 with AI success rate

## Error Handling
- Use typed, domain-specific errors, not generic Error or string throws
- Include: error code, user message, context, retryable flag
- Handle errors at the right abstraction level, never catch-and-ignore

## Architecture
- Explicit dependency injection, no hidden global state
- Dependencies flow one direction only (no circular imports)
- Each module has a single entry point (index.ts or equivalent)
- Keep files 150-400 lines. Split if larger
- Research: +40% code localization improvement (LocAgent, ACL 2025)

## When Creating New Files or Modules
Before writing code for new files or modules, call get_checklist() from ai-native MCP tools
for a comprehensive quality review covering all 10 categories.
For deeper guidance on specific topics, call get_guide("naming"), get_guide("error-handling"), etc.`;

      expect(agentsMdContent).toMatch(/^#/);
      expect(agentsMdContent).not.toMatch(/^---/);
      const lines = agentsMdContent.split('\n');
      expect(lines.length).toBeLessThanOrEqual(50);
    });
  });
});
